### ISSUE TITLE
Add support for more duration formats

### ISSUE THREAD

**Issue by klaas-oetken** [habecker/jira-timetracking-cli#8]
Steps to reproduce:
1. call book-time with `-duration 1h` (instead of the usual `1h00m`)

Actual behavior:
An error occurs
```
Traceback (most recent call last):
  File "book-time", line 74, in <module>
  File "arguments.py", line 152, in parse
arguments.ArgumentError: Validator of type regex failed for argument duration
```

Expected behavior:
A time of 1 hour should be booked with no error.

**Comment by habecker** [comment]
Should now be fixed 👍
